=== xemepav/BooksApp/BooksApp/App_Data/Books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 sp2 (x64) (http://www.altova.com) by Dmitry Batalov (Fastdev AB) -->
<!-- W3C Schema generated by XMLSpy v2015 sp2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Books">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Book" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ISBN">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="\d{3}-\d-\d{2}-\d{6}-\d"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Author">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="256"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Title">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="1024"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xemepav/BooksApp/BooksApp/App_Data/Books.xml
<?xml version="1.0" encoding="UTF-8"?>
<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Books.xsd">
	<Book>
		<ISBN>978-3-16-148410-0</ISBN>
		<Author>John Doe</Author>
		<Title>John's Life</Title>
	</Book>
	<Book>
		<ISBN>978-3-16-148410-1</ISBN>
		<Author>John Doe</Author>
		<Title>John's Life Second Edition</Title>
	</Book>
	<Book>
		<ISBN>978-3-16-148410-2</ISBN>
		<Author>John Doe</Author>
		<Title>John's Life Director's Cut</Title>
	</Book>
</Books>
